version: '3.3'

services:
  postgres:
    container_name: postgres_container2
    image: postgres:14
    environment:
      POSTGRES_DB: "mydatabase"
      POSTGRES_USER: "xenous"
      POSTGRES_PASSWORD: "xenous"
    ports:
      - "6444:5432"