// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: grpc.proto

package grpcGenerated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Greeter_CreateAcc_FullMethodName = "/main.Greeter/createAcc"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	CreateAcc(ctx context.Context, in *UserInputRequest, opts ...grpc.CallOption) (*Reply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) CreateAcc(ctx context.Context, in *UserInputRequest, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Greeter_CreateAcc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility.
type GreeterServer interface {
	CreateAcc(context.Context, *UserInputRequest) (*Reply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterServer struct{}

func (UnimplementedGreeterServer) CreateAcc(context.Context, *UserInputRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAcc not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}
func (UnimplementedGreeterServer) testEmbeddedByValue()                 {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	// If the following call pancis, it indicates UnimplementedGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_CreateAcc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateAcc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_CreateAcc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateAcc(ctx, req.(*UserInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createAcc",
			Handler:    _Greeter_CreateAcc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

const (
	FindUser_FindAccountID_FullMethodName = "/main.FindUser/FindAccountID"
)

// FindUserClient is the client API for FindUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindUserClient interface {
	FindAccountID(ctx context.Context, in *UserNameInput, opts ...grpc.CallOption) (*ReplyName, error)
}

type findUserClient struct {
	cc grpc.ClientConnInterface
}

func NewFindUserClient(cc grpc.ClientConnInterface) FindUserClient {
	return &findUserClient{cc}
}

func (c *findUserClient) FindAccountID(ctx context.Context, in *UserNameInput, opts ...grpc.CallOption) (*ReplyName, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyName)
	err := c.cc.Invoke(ctx, FindUser_FindAccountID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindUserServer is the server API for FindUser service.
// All implementations must embed UnimplementedFindUserServer
// for forward compatibility.
type FindUserServer interface {
	FindAccountID(context.Context, *UserNameInput) (*ReplyName, error)
	mustEmbedUnimplementedFindUserServer()
}

// UnimplementedFindUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindUserServer struct{}

func (UnimplementedFindUserServer) FindAccountID(context.Context, *UserNameInput) (*ReplyName, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAccountID not implemented")
}
func (UnimplementedFindUserServer) mustEmbedUnimplementedFindUserServer() {}
func (UnimplementedFindUserServer) testEmbeddedByValue()                  {}

// UnsafeFindUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindUserServer will
// result in compilation errors.
type UnsafeFindUserServer interface {
	mustEmbedUnimplementedFindUserServer()
}

func RegisterFindUserServer(s grpc.ServiceRegistrar, srv FindUserServer) {
	// If the following call pancis, it indicates UnimplementedFindUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindUser_ServiceDesc, srv)
}

func _FindUser_FindAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNameInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindUserServer).FindAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindUser_FindAccountID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindUserServer).FindAccountID(ctx, req.(*UserNameInput))
	}
	return interceptor(ctx, in, info, handler)
}

// FindUser_ServiceDesc is the grpc.ServiceDesc for FindUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.FindUser",
	HandlerType: (*FindUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAccountID",
			Handler:    _FindUser_FindAccountID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
